### ISSUE TITLE
Create a list of failure reasons

### ISSUE THREAD

**Issue by jdeck88** [Biomatters/biocode-lims#138]
We want a list of semantically defined reasons for Failure.. Need to peruse assembly notes for why a sequence failed. 

- [ ] list of failed reasons
- [ ] add an option to view the failure reasons... Under "Mark as Fail" replace "Notes" with "failed reasons list".  This is stored in assembly notes.

**Comment by steierj** [comment]
<img width="483" alt="Screen Shot 2023-08-14 at 1 36 33 PM" src="https://github.com/biocodellc/biocode-lims/assets/74207845/b4131164-05a0-4274-8f6e-de83a210715f">


Here is the window where users add the failed reason/notes. We would want there to be a dropdown menu with options in the "Reason" field, which is grey-ed out and not accessible in this screenshot.

**Comment by jdeck88** [comment]
Attaching two files here, a list of fail_reasons.csv and notes.csv.... these are two fields that contain some information around possible failure---- These files are grouped by value with counts showing number of times they appear.

The first file below is more informative.
[fail_reasons.csv](https://github.com/biocodellc/biocode-lims/files/13239416/fail_reasons.csv)
[notes.csv](https://github.com/biocodellc/biocode-lims/files/13239415/notes.csv)

In general, messages mostly talk about poor quality of sequences, failed or poor assembly, and contamination.  Unsure where to draw the lines here.

**Comment by jdeck88** [comment]
Niamh, Sarah and Chris suggested the following vocabulary:

Did Not Assemble
--
Assembled but low quality
Assembled but non target sequence: Bacteria
Assembled but non target sequence: Other Eukaryote
Assembled but non target sequence: Cross contamination
Assembled but non target sequence: Pseudogene
Assembled but non target sequence: Reason unknown
Assembled but duplicate sequence (e.g., rerun) is better

**Comment by jdeck88** [comment]
Added list of failure reasons to nmnh-lims database table.  
All functionality will be expressed in the current plugin release.
