### ISSUE TITLE
Annotation with FIMS/LIMS data field detection error

### ISSUE THREAD

**Issue by steierj** [Biomatters/biocode-lims#139]
When annotating local documents in Geneious with any of the options in either function "Annotate with FIMS/LIMS data..." OR "Annotate with FIMS data only...", there seems to be a disconnect between GEOME and Biocode LIMS where LIMS cannot pull data from certain current GEOME FIMS fields. Specifically, I have noticed with the fields "voucherCatalogNumber", "class", "tissueCatalogNumber" and "tissueBarcode", though there may be others.

To replicate:
For local documents that were previously annotated before this disconnect came about and have data in these fields, highlight the document and perform any annotation with FIMS or FIM/LIMS function. 

<img width="1354" alt="Screen Shot 2023-08-14 at 2 47 37 PM" src="https://github.com/biocodellc/biocode-lims/assets/74207845/65620963-c4c0-43e8-a906-5e3ca2e365d2">

<img width="1415" alt="Screen Shot 2023-08-14 at 2 47 25 PM" src="https://github.com/biocodellc/biocode-lims/assets/74207845/f6cd861a-b197-4617-a858-e0b3745c3287">

If any of the above mentioned fields were previously annotated, this notice now pops up:

<img width="1316" alt="Screen Shot 2023-08-14 at 2 52 42 PM" src="https://github.com/biocodellc/biocode-lims/assets/74207845/75422c9a-31cb-43a9-bb88-4e78c62b0960">

if you choose "Remove Fields", those fields become empty on the Local Geneious document and further FIMS/LIMS annotation will NOT pull this data again from GEOME, even if it is present.

**Comment by jdeck88** [comment]
In order to replicate this issue, i will need a copy of some local data that reproduces this problem.... can you send this to me @steierj ?

**Comment by jdeck88** [comment]
Thanks Julia for providing Example data to replicate issue.... These fields were either not added or removed from a refactor some versions ago.  I added them to the list in the LIMS and now things work.
