### ISSUE TITLE
bulk add concentrations

### ISSUE THREAD

**Issue by jdeck88** [Biomatters/biocode-lims#141]
add ability to bulk add concentration based on Plate Well via text file (same method as adding 2D barcodes to the extraction plate under "Bulk Edit" when looking at extraction plates in Biocode LIMS)  
@tweeds volunteers to help with this

**Comment by tweedts** [comment]
Reviewed with John over zoom and demonstrated how the plate Bulk Edit feature allows uploading extraction plate barcodes from a text file. We would like to bulk edit field Concentration/Purity in the same way. There may be a wrinkle in that field Concentration/Purity is dependent upon a Yes value in field Sample Spec'd.

Example of the text file used for bulk upload of plate barcodes attached. Mock text file for hypothetical bulk upload of concentration data also attached.
[PCYC_01_14-Jun-2022_03-43-20 PM.txt](https://github.com/biocodellc/biocode-lims/files/13998658/PCYC_01_14-Jun-2022_03-43-20.PM.txt)
[mock_bulk_concen_upload.txt](https://github.com/biocodellc/biocode-lims/files/13998672/mock_bulk_concen_upload.txt)

**Comment by jdeck88** [comment]
Question from Jan 22nd Tech Meeting (@steierj @tweedts @chrispmeyer among others present):
What happens if "Spec" = N and we want to bulk upload concentrations? 
Automatically turn "Spec" = Y for when we have a concentration of 0 or above in the bulk uploaded data.

**Comment by jdeck88** [comment]
This is solved with recent commit ee77a09  will appear with next plugin release
