### ISSUE TITLE
Missing sequence failure reason from pick-list

### ISSUE THREAD

**Issue by tweedts** [Biomatters/biocode-lims#143]
Re-visiting closed issue #138. 
I have updated my plugin and am about to fail sequences in the LIMS.
When failing sequences, the pick-list is missing a key failure reason: "Did not assemble".
Please add this failure reason as the first choice in the pick-list after "Unspecified".

<img width="644" alt="Screen Shot 2024-01-20 at 11 49 12 AM" src="https://github.com/biocodellc/biocode-lims/assets/81374390/31a585b9-3ab7-42c6-9948-ccee6045e886">

**Comment by jdeck88** [comment]
I added this to recent commit 12851de to sort in the right way (as specified above).  this will NOT come out immediately but will need to wait for next plugin release.  Meanwhile, the option will appear on the bottom of the list.
